# Setup
title:        HeeJung Hwang blog
tagline:      beyond the Reality
baseurl:      "/blog"
paginate:     1

# About/contact
author:
  name:       HeeJung Hwang
  url:        https://heejunghwang.github.io/blog/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
